INHERIT: /zon/common_config.yaml
site_name: zappi
repo_url: https://github.com/ZeitOnline/docs-zappi

nav:
    - index.md
    - overview.md
    - onboarding.md
    - codingstyle.md
    - operations.md
    - validation.md
    - API: api.md
