name: Release api docs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/api/**'
      - '.github/workflows/release-api-docs.yaml'

jobs:
  release:
    name: Release Swagger
    runs-on: zon-ubuntu-general-dind
    if: contains(github.repository, 'ZeitOnline')
    env:
      RELEASE_TAG: api-docs-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "docs/api/package-lock.json"

      - name: Install dependencies
        run: |
          cd docs/api
          npm ci --ignore-scripts

      - name: Pack artifacts
        run: tar -czf swagger-api-docs.tar.gz -C docs/api api.yaml swagger.html node_modules/swagger-ui-dist

      - name: Update release tag
        run: |
          git fetch origin +refs/tags/${{ env.RELEASE_TAG}}:refs/tags/${{ env.RELEASE_TAG }}
          git tag -d ${{ env.RELEASE_TAG }}
          git push origin :refs/tags/${{ env.RELEASE_TAG }}
          git tag -f ${{ env.RELEASE_TAG }}
          git push origin ${{ env.RELEASE_TAG }}

      - name: Release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          files: swagger-api-docs.tar.gz


  trigger:
    name: Trigger main docs build
    runs-on: zon-ubuntu-general-dind
    if: contains(github.repository, 'ZeitOnline')
    needs: release

    steps:
      - name: Trigger Repository Dispatch in docs
        uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # v3.0.0
        with:
          token: ${{ secrets.PRIVATE_REPO_ACCESS_PAT }}
          repository: ZeitOnline/docs
          event-type: module-commit
          client-payload: '{"repo": "${{ github.repository }}", "ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
