name: Testrunner

on:
  push:
    branches:
      - "main"
  pull_request:

env:
  PROJECT: zappi-spec
  BUILD_URL: "${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}"

jobs:
  test:
    runs-on: zon-ubuntu-general-dind
    permissions:
      contents: "read"

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version: "3.14"

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "docs/api/package-lock.json"

      - run: bin/test

      - uses: slackapi/slack-github-action@dcb1066f776dd043e64d0e8ba94ca15cc7e1875d # v4
        if: failure() && github.ref_name == 'main'
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{secrets.SLACK_TEAM_CONTENT_CHANNEL_ID}}
            text: ":small_red_triangle_down: <${{env.BUILD_URL}}|${{env.PROJECT}}> tests failed"
